image: docker:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker build -t my-backend-image .

test:
  stage: test
  script:
    - docker run --rm my-backend-image /bin/bash -c "npm test"

deploy:
  stage: deploy
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push my-backend-image:$CI_COMMIT_TAG
  only:
    - tags